% problemset.sty
%  Presents academic assignment solutions for given problems
% 2018 March 18th Nicholas A. Buckeridge bucknich@gmail.com

% -- Use article settings as base class
\LoadClass[11pt, a4paper, titlepage]{article}


% -- Class definition
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{problemset}

% -- class packages
\RequirePackage[margin=20mm]{geometry}

% -- Class options
\ProcessOptions\relax
